backend:
  name: github
  repo: greensteph/student-study-tool
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Science, name: science, widget: object, collapsed: true, fields: [{label: Heading, name: heading, widget: string}, {label: Flashcards, name: flashcards, widget: list, fields: [{label: Question, name: question, widget: text}, {label: Answer, name: answer, widget: text}]}]}
          - {label: Language, name: language, widget: object, collapsed: true, fields: [{label: Heading, name: heading, widget: string}, {label: Flashcards, name: flashcards, widget: list, fields: [{label: Question, name: question, widget: text}, {label: Answer, name: answer, widget: text}]}]}
          - {label: Math, name: math, widget: object, collapsed: true, fields: [{label: Heading, name: heading, widget: string}, {label: Flashcards, name: flashcards, widget: list, fields: [{label: Question, name: question, widget: text}, {label: Answer, name: answer, widget: text}]}]}
          